pipeline:
  name: CD_DD
  identifier: CD_DD
  projectIdentifier: Dmitrii_Rezba_test
  orgIdentifier: fss_apollo
  tags: {}
  stages:
    - stage:
        name: Deloty
        identifier: Deloty
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: datadog_test
          environment:
            environmentRef: ENV_datadog
            deployToAll: false
            infrastructureDefinitions:
              - identifier: Infra_DD
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
