apiVersion: apps/v1
kind: Deployment
metadata:
  name: 'apollo-backend-videostream-test'
  labels:
    app: 'apollo-backend-videostream-test'
  annotations:
    ad.datadoghq.com/tags: '{"IndexInfo": "true", "IndexDebug": "true", "IndexTrace": "true"}'
spec:
  replicas: 2
  selector:
    matchLabels:
      app: 'apollo-backend-videostream-test'
  template:
    metadata:
      labels:
        app: 'apollo-backend-videostream-test'
    spec:
      imagePullSecrets:
        - name: 'YSCCO48N79XLLQ40R35PSC4CV32T4VTPJU336CVU7KJJKOZ1T3KYLSS28RYY295A'
      securityContext: {}
      containers:
        - name: 'apollo-backend-videostream-test'
          image: 'quay.apps.mgmt-1.hydra.verint.com/fss/apollo-backend-videostream:latest'
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            periodSeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            timeoutSeconds: 10
          startupProbe:
            httpGet:
              path: /health/startup
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 10
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: K8S_NAMESPACE
              value: "fss-apollo-main-dmitrii"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: 'apollo-backend-videostream-test'
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: 'apollo-backend-videostream-test'
                  key: aws_secret_access_key
            - name: AWS_DEFAULT_REGION
              valueFrom:
                configMapKeyRef:
                  name: 'apollo-backend-videostream-test'
                  key: aws_default_region
            - name: MICROSERVICE_URL_DASHBOARD
              valueFrom:
                configMapKeyRef:
                  name: 'apollo-backend-videostream-test'
                  key: microservice_url_dashboard
            - name: MICROSERVICE_URL_DEVICEMANAGER
              valueFrom:
                configMapKeyRef:
                  name: 'apollo-backend-videostream-test'
                  key: microservice_url_devicemanager
            - name: MICROSERVICE_URL_VIDEOSTREAM
              valueFrom:
                configMapKeyRef:
                  name: 'apollo-backend-videostream-test'
                  key: microservice_url_videostream
---
apiVersion: v1
kind: Service
metadata:
  name: 'apollo-backend-videostream-test'
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: 'apollo-backend-videostream-test'
---
apiVersion: v1
kind: Secret
metadata:
  name: 'apollo-backend-videostream-test'
data:
  aws_access_key_id: "QUtJQTJPTFRJVUVCTEZHRTVVT0o="
  aws_secret_access_key: "dXo2aWNtNmJ4MlFqK1BzMWNyS3A4VktBcUZpUkxUSG56VEMxYlhJaEg="
